// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuf/exchange-wallet.proto

package exchange_wallet_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnCode int32

const (
	ReturnCode_ERROR   ReturnCode = 0
	ReturnCode_SUCCESS ReturnCode = 1
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0: "ERROR",
		1: "SUCCESS",
	}
	ReturnCode_value = map[string]int32{
		"ERROR":   0,
		"SUCCESS": 1,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_exchange_wallet_proto_enumTypes[0].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_protobuf_exchange_wallet_proto_enumTypes[0]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{0}
}

// EOA 账户热钱包公钥
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// EOA 热钱包地址
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 代币
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decimals      uint32                 `protobuf:"varint,1,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenName     string                 `protobuf:"bytes,3,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	CollectAmount string                 `protobuf:"bytes,4,opt,name=collect_amount,json=collectAmount,proto3" json:"collect_amount,omitempty"`
	ColdAmount    string                 `protobuf:"bytes,5,opt,name=cold_amount,json=coldAmount,proto3" json:"cold_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Token) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Token) GetCollectAmount() string {
	if x != nil {
		return x.CollectAmount
	}
	return ""
}

func (x *Token) GetColdAmount() string {
	if x != nil {
		return x.ColdAmount
	}
	return ""
}

// 项目方注册请求
type BusinessRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,3,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterRequest) Reset() {
	*x = BusinessRegisterRequest{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterRequest) ProtoMessage() {}

func (x *BusinessRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterRequest.ProtoReflect.Descriptor instead.
func (*BusinessRegisterRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *BusinessRegisterRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *BusinessRegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BusinessRegisterRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

// 项目方注册响应
type BusinessRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRegisterResponse) Reset() {
	*x = BusinessRegisterResponse{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRegisterResponse) ProtoMessage() {}

func (x *BusinessRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRegisterResponse.ProtoReflect.Descriptor instead.
func (*BusinessRegisterResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *BusinessRegisterResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *BusinessRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 地址导出请求
type ExportAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PublicKeys    []*PublicKey           `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressRequest) Reset() {
	*x = ExportAddressRequest{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressRequest) ProtoMessage() {}

func (x *ExportAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressRequest.ProtoReflect.Descriptor instead.
func (*ExportAddressRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ExportAddressRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *ExportAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExportAddressRequest) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

// 地址导出响应
type ExportAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAddressResponse) Reset() {
	*x = ExportAddressResponse{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAddressResponse) ProtoMessage() {}

func (x *ExportAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAddressResponse.ProtoReflect.Descriptor instead.
func (*ExportAddressResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *ExportAddressResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *ExportAddressResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportAddressResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// 创建未签名交易
type UnSignTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken   string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChainId         string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Chain           string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	From            string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Value           string                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	ContractAddress string                 `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string                 `protobuf:"bytes,9,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenMeta       string                 `protobuf:"bytes,10,opt,name=token_meta,json=tokenMeta,proto3" json:"token_meta,omitempty"`
	TxType          string                 `protobuf:"bytes,11,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnSignTransactionRequest) Reset() {
	*x = UnSignTransactionRequest{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSignTransactionRequest) ProtoMessage() {}

func (x *UnSignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSignTransactionRequest.ProtoReflect.Descriptor instead.
func (*UnSignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *UnSignTransactionRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *UnSignTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnSignTransactionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *UnSignTransactionRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *UnSignTransactionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *UnSignTransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *UnSignTransactionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UnSignTransactionRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *UnSignTransactionRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UnSignTransactionRequest) GetTokenMeta() string {
	if x != nil {
		return x.TokenMeta
	}
	return ""
}

func (x *UnSignTransactionRequest) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

// 未签名交易响应
type UnSignTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UnSignTx      string                 `protobuf:"bytes,4,opt,name=un_sign_tx,json=unSignTx,proto3" json:"un_sign_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnSignTransactionResponse) Reset() {
	*x = UnSignTransactionResponse{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnSignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnSignTransactionResponse) ProtoMessage() {}

func (x *UnSignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnSignTransactionResponse.ProtoReflect.Descriptor instead.
func (*UnSignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *UnSignTransactionResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *UnSignTransactionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UnSignTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UnSignTransactionResponse) GetUnSignTx() string {
	if x != nil {
		return x.UnSignTx
	}
	return ""
}

// 已签名交易请求
type SignedTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	ChainId       string                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	TxType        string                 `protobuf:"bytes,7,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionRequest) Reset() {
	*x = SignedTransactionRequest{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionRequest) ProtoMessage() {}

func (x *SignedTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignedTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *SignedTransactionRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *SignedTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignedTransactionRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *SignedTransactionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *SignedTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SignedTransactionRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedTransactionRequest) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

// 已签名交易响应
type SignedTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	SignedTx      string                 `protobuf:"bytes,3,opt,name=signed_tx,json=signedTx,proto3" json:"signed_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransactionResponse) Reset() {
	*x = SignedTransactionResponse{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransactionResponse) ProtoMessage() {}

func (x *SignedTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignedTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *SignedTransactionResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *SignedTransactionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SignedTransactionResponse) GetSignedTx() string {
	if x != nil {
		return x.SignedTx
	}
	return ""
}

type SetTokenAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenList     []*Token               `protobuf:"bytes,2,rep,name=token_list,json=tokenList,proto3" json:"token_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTokenAddressRequest) Reset() {
	*x = SetTokenAddressRequest{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenAddressRequest) ProtoMessage() {}

func (x *SetTokenAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenAddressRequest.ProtoReflect.Descriptor instead.
func (*SetTokenAddressRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *SetTokenAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetTokenAddressRequest) GetTokenList() []*Token {
	if x != nil {
		return x.TokenList
	}
	return nil
}

type SetTokenAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ReturnCode             `protobuf:"varint,1,opt,name=code,proto3,enum=syncs.ReturnCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTokenAddressResponse) Reset() {
	*x = SetTokenAddressResponse{}
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenAddressResponse) ProtoMessage() {}

func (x *SetTokenAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_exchange_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenAddressResponse.ProtoReflect.Descriptor instead.
func (*SetTokenAddressResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_exchange_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *SetTokenAddressResponse) GetCode() ReturnCode {
	if x != nil {
		return x.Code
	}
	return ReturnCode_ERROR
}

func (x *SetTokenAddressResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protobuf_exchange_wallet_proto protoreflect.FileDescriptor

const file_protobuf_exchange_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/exchange-wallet.proto\x12\x05syncs\">\n" +
	"\tPublicKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"7\n" +
	"\aAddress\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xa4\x01\n" +
	"\x05Token\x12\x1a\n" +
	"\bdecimals\x18\x01 \x01(\rR\bdecimals\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x03 \x01(\tR\ttokenName\x12%\n" +
	"\x0ecollect_amount\x18\x04 \x01(\tR\rcollectAmount\x12\x1f\n" +
	"\vcold_amount\x18\x05 \x01(\tR\n" +
	"coldAmount\"~\n" +
	"\x17BusinessRegisterRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x03 \x01(\tR\tnotifyUrl\"S\n" +
	"\x18BusinessRegisterResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x8f\x01\n" +
	"\x14ExportAddressRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x121\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x10.syncs.PublicKeyR\n" +
	"publicKeys\"~\n" +
	"\x15ExportAddressResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\taddresses\x18\x03 \x03(\v2\x0e.syncs.AddressR\taddresses\"\xc9\x02\n" +
	"\x18UnSignTransactionRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12)\n" +
	"\x10contract_address\x18\b \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\t \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"token_meta\x18\n" +
	" \x01(\tR\ttokenMeta\x12\x17\n" +
	"\atx_type\x18\v \x01(\tR\x06txType\"\x99\x01\n" +
	"\x19UnSignTransactionResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1c\n" +
	"\n" +
	"un_sign_tx\x18\x04 \x01(\tR\bunSignTx\"\xef\x01\n" +
	"\x18SignedTransactionRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\tR\achainId\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x17\n" +
	"\atx_type\x18\a \x01(\tR\x06txType\"q\n" +
	"\x19SignedTransactionResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tsigned_tx\x18\x03 \x01(\tR\bsignedTx\"d\n" +
	"\x16SetTokenAddressRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\n" +
	"token_list\x18\x02 \x03(\v2\f.syncs.TokenR\ttokenList\"R\n" +
	"\x17SetTokenAddressResponse\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.syncs.ReturnCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*$\n" +
	"\n" +
	"ReturnCode\x12\t\n" +
	"\x05ERROR\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x012\xd1\x03\n" +
	"\x16WalletBusinessServices\x12S\n" +
	"\x10businessRegister\x12\x1e.syncs.BusinessRegisterRequest\x1a\x1f.syncs.BusinessRegisterResponse\x12V\n" +
	"\x19exportAddressByPublicKeys\x12\x1b.syncs.ExportAddressRequest\x1a\x1c.syncs.ExportAddressResponse\x12[\n" +
	"\x16buildUnSignTransaction\x12\x1f.syncs.UnSignTransactionRequest\x1a .syncs.UnSignTransactionResponse\x12[\n" +
	"\x16buildSignedTransaction\x12\x1f.syncs.SignedTransactionRequest\x1a .syncs.SignedTransactionResponse\x12P\n" +
	"\x0fsetTokenAddress\x12\x1d.syncs.SetTokenAddressRequest\x1a\x1e.syncs.SetTokenAddressResponseB\x1fZ\x1d./protobuf/exchange-wallet-gob\x06proto3"

var (
	file_protobuf_exchange_wallet_proto_rawDescOnce sync.Once
	file_protobuf_exchange_wallet_proto_rawDescData []byte
)

func file_protobuf_exchange_wallet_proto_rawDescGZIP() []byte {
	file_protobuf_exchange_wallet_proto_rawDescOnce.Do(func() {
		file_protobuf_exchange_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_exchange_wallet_proto_rawDesc), len(file_protobuf_exchange_wallet_proto_rawDesc)))
	})
	return file_protobuf_exchange_wallet_proto_rawDescData
}

var file_protobuf_exchange_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_exchange_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protobuf_exchange_wallet_proto_goTypes = []any{
	(ReturnCode)(0),                   // 0: syncs.ReturnCode
	(*PublicKey)(nil),                 // 1: syncs.PublicKey
	(*Address)(nil),                   // 2: syncs.Address
	(*Token)(nil),                     // 3: syncs.Token
	(*BusinessRegisterRequest)(nil),   // 4: syncs.BusinessRegisterRequest
	(*BusinessRegisterResponse)(nil),  // 5: syncs.BusinessRegisterResponse
	(*ExportAddressRequest)(nil),      // 6: syncs.ExportAddressRequest
	(*ExportAddressResponse)(nil),     // 7: syncs.ExportAddressResponse
	(*UnSignTransactionRequest)(nil),  // 8: syncs.UnSignTransactionRequest
	(*UnSignTransactionResponse)(nil), // 9: syncs.UnSignTransactionResponse
	(*SignedTransactionRequest)(nil),  // 10: syncs.SignedTransactionRequest
	(*SignedTransactionResponse)(nil), // 11: syncs.SignedTransactionResponse
	(*SetTokenAddressRequest)(nil),    // 12: syncs.SetTokenAddressRequest
	(*SetTokenAddressResponse)(nil),   // 13: syncs.SetTokenAddressResponse
}
var file_protobuf_exchange_wallet_proto_depIdxs = []int32{
	0,  // 0: syncs.BusinessRegisterResponse.code:type_name -> syncs.ReturnCode
	1,  // 1: syncs.ExportAddressRequest.public_keys:type_name -> syncs.PublicKey
	0,  // 2: syncs.ExportAddressResponse.code:type_name -> syncs.ReturnCode
	2,  // 3: syncs.ExportAddressResponse.addresses:type_name -> syncs.Address
	0,  // 4: syncs.UnSignTransactionResponse.code:type_name -> syncs.ReturnCode
	0,  // 5: syncs.SignedTransactionResponse.code:type_name -> syncs.ReturnCode
	3,  // 6: syncs.SetTokenAddressRequest.token_list:type_name -> syncs.Token
	0,  // 7: syncs.SetTokenAddressResponse.code:type_name -> syncs.ReturnCode
	4,  // 8: syncs.WalletBusinessServices.businessRegister:input_type -> syncs.BusinessRegisterRequest
	6,  // 9: syncs.WalletBusinessServices.exportAddressByPublicKeys:input_type -> syncs.ExportAddressRequest
	8,  // 10: syncs.WalletBusinessServices.buildUnSignTransaction:input_type -> syncs.UnSignTransactionRequest
	10, // 11: syncs.WalletBusinessServices.buildSignedTransaction:input_type -> syncs.SignedTransactionRequest
	12, // 12: syncs.WalletBusinessServices.setTokenAddress:input_type -> syncs.SetTokenAddressRequest
	5,  // 13: syncs.WalletBusinessServices.businessRegister:output_type -> syncs.BusinessRegisterResponse
	7,  // 14: syncs.WalletBusinessServices.exportAddressByPublicKeys:output_type -> syncs.ExportAddressResponse
	9,  // 15: syncs.WalletBusinessServices.buildUnSignTransaction:output_type -> syncs.UnSignTransactionResponse
	11, // 16: syncs.WalletBusinessServices.buildSignedTransaction:output_type -> syncs.SignedTransactionResponse
	13, // 17: syncs.WalletBusinessServices.setTokenAddress:output_type -> syncs.SetTokenAddressResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protobuf_exchange_wallet_proto_init() }
func file_protobuf_exchange_wallet_proto_init() {
	if File_protobuf_exchange_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_exchange_wallet_proto_rawDesc), len(file_protobuf_exchange_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_exchange_wallet_proto_goTypes,
		DependencyIndexes: file_protobuf_exchange_wallet_proto_depIdxs,
		EnumInfos:         file_protobuf_exchange_wallet_proto_enumTypes,
		MessageInfos:      file_protobuf_exchange_wallet_proto_msgTypes,
	}.Build()
	File_protobuf_exchange_wallet_proto = out.File
	file_protobuf_exchange_wallet_proto_goTypes = nil
	file_protobuf_exchange_wallet_proto_depIdxs = nil
}
